### ISSUE TITLE
ScrollController for the bar?

### ISSUE THREAD

**Issue by mark8044** [m-azyoksul/bottom_nav_layout#2]
Id like to have the bar scroll away as the user scrolls the screen (something like this: https://pub.dev/packages/scroll_bottom_navigation_bar)

To do this I believe I need to program some animation with a scrollcontroller.

Is there anyway to attach a scrollcontroller to your bar?

PS.  Bar is working outstanding!

**Comment by mark8044** [comment]
Im an idiot.  Lets just leave it at that

**Comment by mt-akar** [comment]
> Is there anyway to attach a scrollcontroller to your bar?

BottomNavLayout doesn't provide a bottom bar, it only provides a layout. You need to create your own bar using the bottom bar builder parameter.

>Id like to have the bar scroll away as the user scrolls the screen (something like this: https://pub.dev/packages/scroll_bottom_navigation_bar)

This behavior should be possible. Just follow that particular bottom bar package's documentation.
